"""add analytics tables

Revision ID: 1fe472d4a34e
Revises: ccdf6bbfd9f1
Create Date: 2026-09-14 17:52:57.645434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fe472d4a34e'
down_revision: Union[str, Sequence[str], None] = 'ccdf6bbfd9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duration_of_stay_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('include_synthetic', sa.Boolean(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('avg_duration_minutes', sa.Float(), nullable=False),
    sa.Column('median_duration_minutes', sa.Float(), nullable=False),
    sa.Column('min_duration_minutes', sa.Float(), nullable=False),
    sa.Column('max_duration_minutes', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_date', 'include_synthetic', name='uq_duration_of_stay_daily_date_source'),
    schema='analytics_schema'
    )
    op.create_index(op.f('ix_analytics_schema_duration_of_stay_daily_include_synthetic'), 'duration_of_stay_daily', ['include_synthetic'], unique=False, schema='analytics_schema')
    op.create_index(op.f('ix_analytics_schema_duration_of_stay_daily_visit_date'), 'duration_of_stay_daily', ['visit_date'], unique=False, schema='analytics_schema')
    op.create_table('hourly_visit_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('include_synthetic', sa.Boolean(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hour_of_day', 'is_weekend', 'include_synthetic', name='uq_hourly_visit_stats_hour_weekend_source'),
    schema='analytics_schema'
    )
    op.create_index(op.f('ix_analytics_schema_hourly_visit_stats_hour_of_day'), 'hourly_visit_stats', ['hour_of_day'], unique=False, schema='analytics_schema')
    op.create_index(op.f('ix_analytics_schema_hourly_visit_stats_include_synthetic'), 'hourly_visit_stats', ['include_synthetic'], unique=False, schema='analytics_schema')
    op.create_index(op.f('ix_analytics_schema_hourly_visit_stats_is_weekend'), 'hourly_visit_stats', ['is_weekend'], unique=False, schema='analytics_schema')
    op.create_table('monthly_visit_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('include_synthetic', sa.Boolean(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', 'include_synthetic', name='uq_monthly_visit_stats_year_month_source'),
    schema='analytics_schema'
    )
    op.create_index(op.f('ix_analytics_schema_monthly_visit_stats_include_synthetic'), 'monthly_visit_stats', ['include_synthetic'], unique=False, schema='analytics_schema')
    op.create_index(op.f('ix_analytics_schema_monthly_visit_stats_month'), 'monthly_visit_stats', ['month'], unique=False, schema='analytics_schema')
    op.create_index(op.f('ix_analytics_schema_monthly_visit_stats_year'), 'monthly_visit_stats', ['year'], unique=False, schema='analytics_schema')
    op.create_table('weekday_visit_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('include_synthetic', sa.Boolean(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_of_week', 'include_synthetic', name='uq_weekday_visit_stats_day_source'),
    schema='analytics_schema'
    )
    op.create_index(op.f('ix_analytics_schema_weekday_visit_stats_day_of_week'), 'weekday_visit_stats', ['day_of_week'], unique=False, schema='analytics_schema')
    op.create_index(op.f('ix_analytics_schema_weekday_visit_stats_include_synthetic'), 'weekday_visit_stats', ['include_synthetic'], unique=False, schema='analytics_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_schema_weekday_visit_stats_include_synthetic'), table_name='weekday_visit_stats', schema='analytics_schema')
    op.drop_index(op.f('ix_analytics_schema_weekday_visit_stats_day_of_week'), table_name='weekday_visit_stats', schema='analytics_schema')
    op.drop_table('weekday_visit_stats', schema='analytics_schema')
    op.drop_index(op.f('ix_analytics_schema_monthly_visit_stats_year'), table_name='monthly_visit_stats', schema='analytics_schema')
    op.drop_index(op.f('ix_analytics_schema_monthly_visit_stats_month'), table_name='monthly_visit_stats', schema='analytics_schema')
    op.drop_index(op.f('ix_analytics_schema_monthly_visit_stats_include_synthetic'), table_name='monthly_visit_stats', schema='analytics_schema')
    op.drop_table('monthly_visit_stats', schema='analytics_schema')
    op.drop_index(op.f('ix_analytics_schema_hourly_visit_stats_is_weekend'), table_name='hourly_visit_stats', schema='analytics_schema')
    op.drop_index(op.f('ix_analytics_schema_hourly_visit_stats_include_synthetic'), table_name='hourly_visit_stats', schema='analytics_schema')
    op.drop_index(op.f('ix_analytics_schema_hourly_visit_stats_hour_of_day'), table_name='hourly_visit_stats', schema='analytics_schema')
    op.drop_table('hourly_visit_stats', schema='analytics_schema')
    op.drop_index(op.f('ix_analytics_schema_duration_of_stay_daily_visit_date'), table_name='duration_of_stay_daily', schema='analytics_schema')
    op.drop_index(op.f('ix_analytics_schema_duration_of_stay_daily_include_synthetic'), table_name='duration_of_stay_daily', schema='analytics_schema')
    op.drop_table('duration_of_stay_daily', schema='analytics_schema')
    # ### end Alembic commands ###
