"""changed observation model for mmc

Revision ID: 4ac78dc79b29
Revises: 7b262fc84013
Create Date: 2025-08-07 09:41:43.671458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac78dc79b29'
down_revision: Union[str, Sequence[str], None] = '7b262fc84013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_observations', sa.Column('make', sa.String(length=30), nullable=True), schema='ingestion_schema')
    op.add_column('vehicle_observations', sa.Column('model', sa.String(length=50), nullable=True), schema='ingestion_schema')
    op.add_column('vehicle_observations', sa.Column('color', sa.String(length=30), nullable=True), schema='ingestion_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_observations', 'color', schema='ingestion_schema')
    op.drop_column('vehicle_observations', 'model', schema='ingestion_schema')
    op.drop_column('vehicle_observations', 'make', schema='ingestion_schema')
    # ### end Alembic commands ###
