"""added municipality

Revision ID: 5dc1a31469ae
Revises: 4ac78dc79b29
Create Date: 2025-08-07 10:29:36.491454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc1a31469ae'
down_revision: Union[str, Sequence[str], None] = '4ac78dc79b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_observations', sa.Column('municipality', sa.String(length=10), nullable=True), schema='ingestion_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_observations', 'municipality', schema='ingestion_schema')
    # ### end Alembic commands ###
