"""added table user preferences

Revision ID: 5dd317ee0af9
Revises: f86019e8a6e8
Create Date: 2025-08-05 07:11:16.507675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd317ee0af9'
down_revision: Union[str, Sequence[str], None] = 'f86019e8a6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('receive_alerts', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('receive_updates', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='notification_schema'
    )
    op.create_index(op.f('ix_notification_schema_user_preferences_name'), 'user_preferences', ['name'], unique=True, schema='notification_schema')
    op.create_index(op.f('ix_notification_schema_user_preferences_receive_alerts'), 'user_preferences', ['receive_alerts'], unique=False, schema='notification_schema')
    op.create_index(op.f('ix_notification_schema_user_preferences_receive_updates'), 'user_preferences', ['receive_updates'], unique=False, schema='notification_schema')
    op.drop_index(op.f('idx_vehicle_observations_plate_hash'), table_name='vehicle_observations', schema='ingestion_schema')
    op.drop_index(op.f('idx_vehicle_observations_timestamp'), table_name='vehicle_observations', schema='ingestion_schema')
    op.create_index(op.f('ix_ingestion_schema_vehicle_observations_plate_hash'), 'vehicle_observations', ['plate_hash'], unique=False, schema='ingestion_schema')
    op.create_index(op.f('ix_ingestion_schema_vehicle_observations_timestamp'), 'vehicle_observations', ['timestamp'], unique=False, schema='ingestion_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_schema_vehicle_observations_timestamp'), table_name='vehicle_observations', schema='ingestion_schema')
    op.drop_index(op.f('ix_ingestion_schema_vehicle_observations_plate_hash'), table_name='vehicle_observations', schema='ingestion_schema')
    op.create_index(op.f('idx_vehicle_observations_timestamp'), 'vehicle_observations', ['timestamp'], unique=False, schema='ingestion_schema')
    op.create_index(op.f('idx_vehicle_observations_plate_hash'), 'vehicle_observations', ['plate_hash'], unique=False, schema='ingestion_schema')
    op.drop_index(op.f('ix_notification_schema_user_preferences_receive_updates'), table_name='user_preferences', schema='notification_schema')
    op.drop_index(op.f('ix_notification_schema_user_preferences_receive_alerts'), table_name='user_preferences', schema='notification_schema')
    op.drop_index(op.f('ix_notification_schema_user_preferences_name'), table_name='user_preferences', schema='notification_schema')
    op.drop_table('user_preferences', schema='notification_schema')
    # ### end Alembic commands ###
