"""drop is_weekend from hourly_visit_stats

Revision ID: 6f9edf78ee41
Revises: 1fe472d4a34e
Create Date: 2026-09-14 18:58:09.752197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9edf78ee41'
down_revision: Union[str, Sequence[str], None] = '1fe472d4a34e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # hourly_visit_stats is a periodically-refreshed cache (see refresh_handler.py), so
    # it's safe - and necessary, since merging the weekday/weekend rows would otherwise
    # collide with the new (hour_of_day, include_synthetic) uniqueness - to clear it here
    # rather than trying to merge old rows; the next scheduled refresh repopulates it.
    op.execute('DELETE FROM analytics_schema.hourly_visit_stats')
    op.drop_index(op.f('ix_analytics_schema_hourly_visit_stats_is_weekend'), table_name='hourly_visit_stats', schema='analytics_schema')
    op.drop_constraint(op.f('uq_hourly_visit_stats_hour_weekend_source'), 'hourly_visit_stats', schema='analytics_schema', type_='unique')
    op.create_unique_constraint('uq_hourly_visit_stats_hour_source', 'hourly_visit_stats', ['hour_of_day', 'include_synthetic'], schema='analytics_schema')
    op.drop_column('hourly_visit_stats', 'is_weekend', schema='analytics_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hourly_visit_stats', sa.Column('is_weekend', sa.BOOLEAN(), autoincrement=False, nullable=False), schema='analytics_schema')
    op.drop_constraint('uq_hourly_visit_stats_hour_source', 'hourly_visit_stats', schema='analytics_schema', type_='unique')
    op.create_unique_constraint(op.f('uq_hourly_visit_stats_hour_weekend_source'), 'hourly_visit_stats', ['hour_of_day', 'is_weekend', 'include_synthetic'], schema='analytics_schema', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_analytics_schema_hourly_visit_stats_is_weekend'), 'hourly_visit_stats', ['is_weekend'], unique=False, schema='analytics_schema')
    # ### end Alembic commands ###
