"""make_user_name_optional

Revision ID: 97b047fbba19
Revises: 5dc1a31469ae
Create Date: 2026-01-30 07:27:03.404335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b047fbba19'
down_revision: Union[str, Sequence[str], None] = '5dc1a31469ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_preferences', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='notification_schema')
    op.drop_index(op.f('ix_notification_schema_user_preferences_name'), table_name='user_preferences', schema='notification_schema')
    op.create_index(op.f('ix_notification_schema_user_preferences_name'), 'user_preferences', ['name'], unique=False, schema='notification_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_schema_user_preferences_name'), table_name='user_preferences', schema='notification_schema')
    op.create_index(op.f('ix_notification_schema_user_preferences_name'), 'user_preferences', ['name'], unique=True, schema='notification_schema')
    op.alter_column('user_preferences', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               schema='notification_schema')
    # ### end Alembic commands ###
