"""added score column

Revision ID: a11d3c920bf3
Revises: 2c41a6b6bac6
Create Date: 2025-07-31 10:50:16.710279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11d3c920bf3'
down_revision: Union[str, Sequence[str], None] = '2c41a6b6bac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_observations', sa.Column('plate_score', sa.Integer(), nullable=True), schema='ingestion_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_observations', 'plate_score', schema='ingestion_schema')
    # ### end Alembic commands ###
