-- Create users with environment variable passwords
CREATE USER notification_user WITH PASSWORD :NOTIFICATION_DB_PASSWORD;
CREATE USER data_collection_user WITH PASSWORD :DATA_COLLECTION_DB_PASSWORD;
CREATE USER analytics_user WITH PASSWORD :ANALYTICS_DB_PASSWORD;

-- Grant database connection privileges
GRANT CONNECT ON DATABASE :DB_NAME TO data_collection_user;
GRANT CONNECT ON DATABASE :DB_NAME TO analytics_user;
GRANT CONNECT ON DATABASE :DB_NAME TO notification_user;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS :DATA_COLLECTION_SCHEMA;
CREATE SCHEMA IF NOT EXISTS :ANALYTICS_SCHEMA;
CREATE SCHEMA IF NOT EXISTS :NOTIFICATION_SCHEMA;

-- Set up Data Collection Service permissions (writes to :DATA_COLLECTION_SCHEMA)
GRANT ALL ON SCHEMA :DATA_COLLECTION_SCHEMA TO data_collection_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA :DATA_COLLECTION_SCHEMA TO data_collection_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA :DATA_COLLECTION_SCHEMA TO data_collection_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA :DATA_COLLECTION_SCHEMA GRANT ALL ON TABLES TO data_collection_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA :DATA_COLLECTION_SCHEMA GRANT ALL ON SEQUENCES TO data_collection_user;

-- Set up Analytics Service permissions (reads from :DATA_COLLECTION_SCHEMA, writes to :ANALYTICS_SCHEMA)
GRANT USAGE ON SCHEMA :DATA_COLLECTION_SCHEMA TO analytics_user;
GRANT SELECT ON ALL TABLES IN SCHEMA :DATA_COLLECTION_SCHEMA TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA :DATA_COLLECTION_SCHEMA GRANT SELECT ON TABLES TO analytics_user;

GRANT ALL ON SCHEMA :ANALYTICS_SCHEMA TO analytics_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA :ANALYTICS_SCHEMA TO analytics_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA :ANALYTICS_SCHEMA TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA :ANALYTICS_SCHEMA GRANT ALL ON TABLES TO analytics_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA :ANALYTICS_SCHEMA GRANT ALL ON SEQUENCES TO analytics_user;

-- Set up notification Service permissions (writes to :NOTIFICATION_SCHEMA)
GRANT ALL ON SCHEMA :NOTIFICATION_SCHEMA TO notification_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA :NOTIFICATION_SCHEMA TO notification_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA :NOTIFICATION_SCHEMA TO notification_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA :NOTIFICATION_SCHEMA GRANT ALL ON TABLES TO notification_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA :NOTIFICATION_SCHEMA GRANT ALL ON SEQUENCES TO notification_user;

-- Set search paths for each user
ALTER ROLE data_collection_user SET search_path = :DATA_COLLECTION_SCHEMA,public;
ALTER ROLE analytics_user SET search_path = :ANALYTICS_SCHEMA,:DATA_COLLECTION_SCHEMA,public;
ALTER ROLE notification_user SET search_path = :NOTIFICATION_SCHEMA,public;